### ISSUE TITLE
dynamic icon look like really bad in android

### ISSUE THREAD

**Issue by outsung** [outsung/expo-dynamic-app-icon#3]
![](https://user-images.githubusercontent.com/22133246/216401044-aecde66b-44b4-4b61-a735-92304f7f4146.png)

maybe because not adaptive icon
or the icon size?

### Todo
- [ ] check adaptive icon
- [ ] check icon size
- [ ] check why background is black

**Comment by hariettem** [comment]
seems launcher dependent. anybody has a workaround?

**Comment by castdrian** [comment]
avoid android I guess

**Comment by Giasinit** [comment]
@outsung you need to see plugin/src/withDynamicIcon.ts at 371-377, there are some references to your problem.
As you can see, the key "backgroundColor" has the value "#ffffff"... maybe if you change it, you will solve your problem.

**Comment by castdrian** [comment]
Discord and N26 somehow do it perfectly fine, so there definitely has to be a working solution somewhere
